# Generated by Django 5.2.4 on 2025-08-04 18:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubtitleStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("css_class", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Subtitle Style",
                "verbose_name_plural": "Subtitle Styles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubtitleProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "video_file",
                    models.FileField(
                        upload_to="videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "avi", "mov", "mkv", "webm"]
                            )
                        ],
                    ),
                ),
                ("video_duration", models.FloatField(blank=True, null=True)),
                ("video_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitle_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtitle Project",
                "verbose_name_plural": "Subtitle Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubtitleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.FloatField(help_text="Start time in seconds")),
                ("end_time", models.FloatField(help_text="End time in seconds")),
                ("text", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, help_text="AI confidence score (0-1)", null=True
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this subtitle has been manually edited",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitle_entries",
                        to="custom.subtitleproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtitle Entry",
                "verbose_name_plural": "Subtitle Entries",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="SubtitleExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("srt", "SRT"),
                            ("vtt", "VTT"),
                            ("ass", "ASS"),
                            ("txt", "TXT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="exports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="custom.subtitleproject",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custom.subtitlestyle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtitle Export",
                "verbose_name_plural": "Subtitle Exports",
                "ordering": ["-created_at"],
            },
        ),
    ]
