# Generated by Django 5.2.4 on 2025-08-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_avatar_url_userprofile_oauth_provider_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="oauth_provider",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="oauth_provider_id",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="oauth_provider_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
