# Generated by Django 5.2.4 on 2025-08-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_account_created_at_user_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_issuer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="google_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
